-- MySQL Script generated by MySQL Workbench
-- Fri Jul  2 14:30:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BuildControlSchema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BuildControlSchema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BuildControlSchema` DEFAULT CHARACTER SET utf8 ;
USE `BuildControlSchema` ;

-- -----------------------------------------------------
-- Table `BuildControlSchema`.`projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuildControlSchema`.`projet` (
  `uuid` VARCHAR(36) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `etat` VARCHAR(45) NOT NULL,
  `dateDebut` DATETIME NOT NULL,
  `dateFin` DATETIME NULL,
  `ville` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuildControlSchema`.`chantier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuildControlSchema`.`chantier` (
  `uuid` VARCHAR(36) NOT NULL,
  `uuidProjet` VARCHAR(36) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_chantier_projet1_idx` (`uuidProjet` ASC),
  CONSTRAINT `fk_chantier_projet1`
    FOREIGN KEY (`uuidProjet`)
    REFERENCES `BuildControlSchema`.`projet` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuildControlSchema`.`metier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuildControlSchema`.`metier` (
  `uuid` VARCHAR(36) NOT NULL,
  `nom` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuildControlSchema`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuildControlSchema`.`utilisateur` (
  `identifiant` VARCHAR(15) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `role` CHAR(1) NOT NULL,
  `mdp` VARCHAR(300) NOT NULL,
  `dateCreationCompte` YEAR(4) NOT NULL,
  `statut` TINYINT(1) NOT NULL,
  `uuidMetier` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`identifiant`),
  INDEX `fk_utilisateur_metier1_idx` (`uuidMetier` ASC),
  CONSTRAINT `fk_utilisateur_metier1`
    FOREIGN KEY (`uuidMetier`)
    REFERENCES `BuildControlSchema`.`metier` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuildControlSchema`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuildControlSchema`.`equipe` (
  `uuid` VARCHAR(36) NOT NULL,
  `responsable_identifiant` VARCHAR(15) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_equipe_utilisateur1_idx` (`responsable_identifiant` ASC),
  CONSTRAINT `fk_equipe_utilisateur1`
    FOREIGN KEY (`responsable_identifiant`)
    REFERENCES `BuildControlSchema`.`utilisateur` (`identifiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuildControlSchema`.`capture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuildControlSchema`.`capture` (
  `uuid` VARCHAR(36) NOT NULL,
  `dateCapture` DATETIME NOT NULL,
  `coordonneesGPS` VARCHAR(100) NOT NULL,
  `media` VARCHAR(100) NULL,
  `url` VARCHAR(150) NULL,
  `etapeCapture` VARCHAR(100) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `jalon` VARCHAR(100) NOT NULL,
  `referenceCapture` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuildControlSchema`.`sous-traitant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuildControlSchema`.`sous-traitant` (
  `uuid` VARCHAR(36) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `numeroTelephone` VARCHAR(10) NOT NULL,
  `uuidMetier` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_sous-traitant_metier1_idx` (`uuidMetier` ASC),
  CONSTRAINT `fk_sous-traitant_metier1`
    FOREIGN KEY (`uuidMetier`)
    REFERENCES `BuildControlSchema`.`metier` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuildControlSchema`.`affectation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuildControlSchema`.`affectation` (
  `uuidChantier` VARCHAR(36) NOT NULL,
  `uuidEquipe` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`uuidChantier`, `uuidEquipe`),
  INDEX `fk_chantier_has_equipe2_equipe1_idx` (`uuidEquipe` ASC),
  INDEX `fk_chantier_has_equipe2_chantier1_idx` (`uuidChantier` ASC),
  CONSTRAINT `fk_chantier_has_equipe2_chantier1`
    FOREIGN KEY (`uuidChantier`)
    REFERENCES `BuildControlSchema`.`chantier` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chantier_has_equipe2_equipe1`
    FOREIGN KEY (`uuidEquipe`)
    REFERENCES `BuildControlSchema`.`equipe` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuildControlSchema`.`etapeChantier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuildControlSchema`.`etapeChantier` (
  `uuid` VARCHAR(36) NOT NULL,
  `uuidChantier` VARCHAR(36) NOT NULL,
  `uuidCapture` VARCHAR(36) NOT NULL,
  `incident` VARCHAR(100) NULL,
  INDEX `fk_chantier_has_capture_capture1_idx` (`uuidCapture` ASC),
  INDEX `fk_chantier_has_capture_chantier1_idx` (`uuidChantier` ASC),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `capture_idcapture_UNIQUE` (`uuidCapture` ASC),
  CONSTRAINT `fk_chantier_has_capture_chantier1`
    FOREIGN KEY (`uuidChantier`)
    REFERENCES `BuildControlSchema`.`chantier` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chantier_has_capture_capture1`
    FOREIGN KEY (`uuidCapture`)
    REFERENCES `BuildControlSchema`.`capture` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuildControlSchema`.`intervention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuildControlSchema`.`intervention` (
  `etapeChantier_uuid` VARCHAR(36) NOT NULL,
  `sous-traitant_uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`etapeChantier_uuid`, `sous-traitant_uuid`),
  INDEX `fk_etapeChantier_has_sous-traitant_sous-traitant1_idx` (`sous-traitant_uuid` ASC),
  INDEX `fk_etapeChantier_has_sous-traitant_etapeChantier1_idx` (`etapeChantier_uuid` ASC),
  CONSTRAINT `fk_etapeChantier_has_sous-traitant_etapeChantier1`
    FOREIGN KEY (`etapeChantier_uuid`)
    REFERENCES `BuildControlSchema`.`etapeChantier` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etapeChantier_has_sous-traitant_sous-traitant1`
    FOREIGN KEY (`sous-traitant_uuid`)
    REFERENCES `BuildControlSchema`.`sous-traitant` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuildControlSchema`.`membreEquipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuildControlSchema`.`membreEquipe` (
  `utilisateur_identifiant` VARCHAR(15) NOT NULL,
  `equipe_uuid` VARCHAR(36) NOT NULL,
  INDEX `fk_utilisateur_has_equipe_equipe1_idx` (`equipe_uuid` ASC),
  INDEX `fk_utilisateur_has_equipe_utilisateur1_idx` (`utilisateur_identifiant` ASC),
  PRIMARY KEY (`utilisateur_identifiant`, `equipe_uuid`),
  CONSTRAINT `fk_utilisateur_has_equipe_utilisateur1`
    FOREIGN KEY (`utilisateur_identifiant`)
    REFERENCES `BuildControlSchema`.`utilisateur` (`identifiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_equipe_equipe1`
    FOREIGN KEY (`equipe_uuid`)
    REFERENCES `BuildControlSchema`.`equipe` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
